### ISSUE TITLE
flaky (pun intended) test runs

### ISSUE THREAD

**Issue by chpill** [Mic92/nixos-test-example#1]
Thanks for this repo, it is very helpful to get started with NixOS tests!

While running `nix flake check -L` on a local clone of this repo, it seems to fail 3 out of 4 runs with `curl: (7) Failed to connect to localhost port 8000 after 61 ms: Couldn't connect to server`.

I have fixed this locally by replacing `node1.wait_for_unit("hello-world-server")` with `node1.wait_for_open_port(8000)`, and it runs consistently after that.

It is a bit disappointing that `node1.wait_for_unit("hello-world-server")` does not actually work here. Is it the service itself signaling its "readiness" too soon?

**Comment by Mic92** [comment]
In an ideal world the python webserver would use systemd socket activation or signal's its readiness using systemd's notify protocol. However in many real-world applications this is not the case so using `output = node1.wait_until_succeeds("curl localhost:8000/index.html")` or `node1.wait_for_open_port(8000)` is the alternative to make nixos tests work.

**Comment by Mic92** [comment]
Done in https://github.com/Mic92/nixos-test-example/commit/098a2a6e9240897ac00572393b1607f006b49af5

**Comment by chpill** [comment]
Thank you for the explanation!
